export enum NotificationType {
  RESERVATION_CONFIRMED = 'RESERVATION_CONFIRMED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  REMINDER_J1 = 'REMINDER_J1',
  RIDE_STARTED = 'RIDE_STARTED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  DRIVER_NEW_RIDE = 'DRIVER_NEW_RIDE',
  DRIVER_RIDE_MODIFIED = 'DRIVER_RIDE_MODIFIED',
  DRIVER_RIDE_CANCELLED = 'DRIVER_RIDE_CANCELLED',
  DRIVER_REMINDER_J1 = 'DRIVER_REMINDER_J1',
}
